.TH chkboot 1 "June 2014" "" "check boot"

.SH NAME
\fBchkboot-check\fP - Notifies about changes in /boot

.SH DESCRIPTION
Displays a warning a the list of changed files if any were detected last time chkboot was run.

.SH AUTHORS
Ju (ju at heisec dot de)

chkboot originally appeared in an article titled "Boot-Sicherung" in [c't magazin's March 2012 issue] [1]. The original author is Juergen Schmidt, ju at heisec.de. The original source code can be found either at the first commit of this repository, or at the [original URL] [2].
.br
[1]: http://www.heise.de/ct/inhalt/2012/03/146/
.br
[2]: http://ftp.heise.de/pub/ct/listings/1203-146.zip
.br

.SH Additional authors:
.br
Inhies (https://github.com/inhies/)
.br
Prurigro (https://github.com/prurigro/)
