.TH chkboot 1 "June 2014" "" "check boot"

.SH NAME
\fBchkboot-desktopalert\fP - Notifies about changes in /boot

.SH DESCRIPTION
Notifies the desktop user about the change and can be included as startup script in the desktop environment or window manager.

.SH AUTHORS
Ju (ju at heisec dot de)

chkboot originally appeared in an article titled "Boot-Sicherung" in [c't magazin's March 2012 issue] [1]. The original author is Juergen Schmidt, ju at heisec.de. The original source code can be found either at the first commit of this repository, or at the [original URL] [2].
.br
[1]: http://www.heise.de/ct/inhalt/2012/03/146/
.br
[2]: http://ftp.heise.de/pub/ct/listings/1203-146.zip
.br

Additional authors:
.br
Inhies (https://github.com/inhies/)
.br
Prurigro (https://github.com/prurigro/)

.SH LICENCE
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
.br
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.br
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
