#!/usr/bin/env bash

source /etc/default/chkboot.conf

source /etc/profile.d/chkboot-diffcheck.sh
if [ "$?" = 1 ]; then echo "Please run chkboot as root again or reboot your computer to clear the list of changed files before attempting to update"; return 1; fi

sudo chkboot && sync
source /etc/profile.d/chkboot-diffcheck.sh
if [ "$?" = 1 ]; then echo "Please review the list of changed files and fix any issues before running chkboot again as root or rebooting when you're ready"; return 1; fi

sudo pacman -Syu

sudo chkboot && sync
source /etc/profile.d/chkboot-diffcheck.sh
if [ "$?" = 1 ]; then
    echo "The changes to your boot partition occurred as a result of the update and were expected; chkboot is running again to clear the list"
    echo "If this list of changed files is needed for any reason, it can still be found in the log file located @ ${CHKBOOT_DATA}/${CHANGES_LOG}"
    sudo chkboot && sync
    return 0
fi
