#!/bin/bash

# small script to check if files under /boot changed
# Author: ju (ju at heisec dot de)
# contributors: Georg Lutz <georg AT NORSPAM georglutz DOT de>
#
# License: GPLv2 or later

source /etc/default/chkboot.conf

chgfile=${CHKBOOT_DATA}/${CHANGES_ALERT}

if [[ -s $chgfile ]] ; then 
    cat $chgfile | zenity --title "ALERT: Boot changes" --text-info --width 500 --height 300
    zenity --title "chkboot" --info --text="This notification will continue to appear until you either run chkboot again as root or restart your computer"
fi

