#!/bin/bash

# small script to check if files under /boot changed
# Author: https://github.com/sercxanto
#
# License: GPLv2 or later

source /etc/default/chkboot.conf

chgfile=${CHKBOOT_DATA}/${CHANGES_ALERT}

XMESSAGE=/usr/bin/xmessage
ZENITY=/usr/bin/zenity
NOTIFICATION="This notification will continue to appear until you\n- either run chkboot again as root\n- or restart your computer"

if [ -s $chgfile ]; then
    if [ -x $ZENITY ]; then
        cat $chgfile | $ZENITY --title "ALERT: Boot changes" --text-info --width 640 --height 480 --no-wrap
        $ZENITY --title "chkboot" --info --height=100 --width=100 --no-wrap --text="$NOTIFICATION"
    elif [ -x $XMESSAGE ]; then
        cat $chgfile | $XMESSAGE -default okay -file -
        $XMESSAGE -default okay $NOTIFICATION
    else
        exit 1
    fi
fi
